import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('zh'),
    Locale('en'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(localizations != null, 'AppLocalizations not found in context');
    return localizations!;
  }

  String t(String key, {Map<String, String> params = const {}}) {
    final language = _localizedValues[locale.languageCode] ?? _localizedValues['zh']!;
    var value = language[key] ?? _localizedValues['en']![key] ?? key;
    params.forEach((name, paramValue) {
      value = value.replaceAll('{$name}', paramValue);
    });
    return value;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'zh': {
      'app.name': 'SmartLab',
      'app.selectLab': '选择实验室',
      'app.notLoggedIn': '未登录',
      'app.openLabSelector': '打开实验室选择',
      'app.labsAndAccount': '实验室与账号',
      'app.language': '语言',
      'app.languageChinese': '中文',
      'app.languageEnglish': 'English',
      'app.smartLabSubtitle': '实验室安全监测',

      'common.cancel': '取消',
      'common.confirm': '确认',
      'common.ok': '确定',
      'common.login': '登录',
      'common.logout': '退出登录',
      'common.submit': '提交',
      'common.search': '搜索',
      'common.on': '开启',
      'common.off': '关闭',
      'common.enable': '启用',
      'common.disable': '停用',

      'nav.home': '首页',
      'nav.environment': '环境',
      'nav.power': '电源',
      'nav.security': '安防',
      'nav.chemicals': '危化品',

      'login.title': '登录',
      'login.helper': '支持学号、工号或管理员账号登录。',
      'login.username': '账号',
      'login.usernameHint': '学号 / 工号 / 用户名',
      'login.enterUsername': '请输入账号',
      'login.password': '密码',
      'login.passwordHint': '请输入密码',
      'login.enterPassword': '请输入密码',
      'login.remember': '记住密码',
      'login.forgotPassword': '忘记密码',
      'login.registerRequest': '提交注册申请',
      'login.passwordResetTitle': '重置密码',
      'login.passwordResetDesc': '请联系实验室管理员重置该账号密码。',
      'login.testAccounts': '测试账号\nadmin / admin123\nteacher / teacher123\ngraduate / graduate123\nstudent / student123',

      'register.title': '注册申请',
      'register.desc': '新账号需管理员审核通过后方可登录。',
      'register.name': '姓名',
      'register.studentOrEmployeeId': '学号 / 工号',
      'register.email': '邮箱',
      'register.enterEmail': '请输入邮箱',
      'register.invalidEmail': '邮箱格式不正确',
      'register.phone': '手机号',
      'register.requestedRole': '申请角色',
      'register.password': '密码',
      'register.confirmPassword': '确认密码',
      'register.atLeast6Chars': '至少 6 位字符',
      'register.passwordMismatch': '两次输入的密码不一致',
      'register.required': '此项不能为空',

      'labSelection.title': '选择实验室',
      'labSelection.desc': '当前版本仅开放项目文档中定义的两个实验室。',
      'labSelection.noAccess': '当前账号未分配实验室权限',
      'labSelection.envCount': '环境 {count}',
      'labSelection.socketCount': '插座 {count}',
      'labSelection.doorCount': '门禁 {count}',
      'labSelection.windowCount': '窗户 {count}',

      'dashboard.currentLab': '当前实验室',
      'dashboard.environment': '环境',
      'dashboard.power': '电源',
      'dashboard.water': '水路',
      'dashboard.doors': '门窗',
      'dashboard.normal': '正常',
      'dashboard.review': '待复核',
      'dashboard.recentAlerts': '最近报警',
      'dashboard.mqttOnline': 'MQTT 在线',
      'dashboard.mqttOffline': 'MQTT 离线',
      'dashboard.noAlerts': '暂无报警',
      'dashboard.ack': '确认',
      'dashboard.safetyScore': '安全评分：{score}',
      'dashboard.pendingAlerts': '待处理报警：{count}',

      'environment.title': '环境监测',
      'environment.evidenceTitle': '环境 AI 取证',
      'environment.evidenceDesc': '硬件传感器不可用时，可通过图像辅助复核。',
      'environment.temp': '温度',
      'environment.humidity': '湿度',
      'environment.tempTrend': '温度趋势',
      'environment.voc': 'VOC {value} ppb',

      'power.title': '电源管理',
      'power.evidenceTitle': '电源 AI 取证',
      'power.evidenceDesc': '可通过图像复核空开、插座与设备电源安全。',
      'power.leakage': '漏电流 {value} mA',
      'power.noPermission': '无设备控制权限',
      'power.confirmShutdownTitle': '确认断电',
      'power.confirmShutdownDesc': '请先确认实验室安全，再执行总电源断电。',
      'power.biometricReason': '断电前请先完成身份验证',
      'power.powerValue': '功率 {value} W',
      'power.voltageValue': '电压 {value} V',
      'power.shutdown': '断电',
      'power.restore': '恢复供电',

      'security.tabWater': '水路',
      'security.tabDoors': '门窗',
      'security.waterEvidenceTitle': '水路 AI 取证',
      'security.waterEvidenceDesc': '通过照片复核阀门、水龙头与渗漏风险。',
      'security.mainValve': '总阀门',
      'security.open': '开启',
      'security.closed': '关闭',
      'security.doorsEvidenceTitle': '门窗 AI 取证',
      'security.doorsEvidenceDesc': '通过照片复核门锁状态与窗户开合角度。',
      'security.locked': '已上锁',
      'security.unlocked': '未上锁',
      'security.windowAngle': '开合角度 {angle}',

      'chem.searchHint': '搜索名称、CAS 或柜位',
      'chem.evidenceTitle': '危化品 AI 取证',
      'chem.evidenceDesc': '采集标签、柜体状态和存储合规证据。',
      'chem.noResults': '当前筛选条件下未找到危化品。',
      'chem.cas': 'CAS：{value}',
      'chem.cabinet': '柜位：{cabinet} / {shelf}',
      'chem.stock': '库存：{quantity} {unit}',
      'chem.hazard': '危险类别：{value}',
      'chem.checkIn': '入库',
      'chem.checkOut': '出库',
      'chem.checkInNote': '详情页手动入库',
      'chem.checkOutNote': '详情页手动出库',

      'alerts.title': '报警中心',
      'alerts.evidenceTitle': '报警 AI 取证',
      'alerts.evidenceDesc': '为待处理报警补充图像与 AI 复核记录。',
      'alerts.ai': 'AI',
      'alerts.ack': '确认',
      'alerts.acked': '已确认',

      'device.detailTitle': '设备详情',
      'device.id': '编号',
      'device.type': '类型',
      'device.status': '状态',
      'device.protocol': '协议',
      'device.firmware': '固件',
      'device.location': '位置',
      'device.evidenceTitle': '设备 AI 取证',
      'device.evidenceDesc': '设备遥测不可用时，可上传照片辅助复核。',
      'device.trend24h': '24 小时趋势',
      'device.unknownDevice': '未知设备',
      'device.unknownLocation': '未知位置',
      'device.currentLab': '当前实验室',
      'deviceStatus.online': '在线',
      'deviceStatus.offline': '离线',
      'deviceStatus.warning': '预警',
      'deviceStatus.error': '故障',

      'evidence.capture': '拍照',
      'evidence.upload': '上传',
      'evidence.noResult': '暂无 AI 结果',
      'evidence.showLatest': '查看最新 AI 结果',
      'evidence.latestTitle': '最新 AI 检测结果',
      'evidence.scene': '场景',
      'evidence.device': '设备',
      'evidence.risk': '风险',
      'evidence.confidence': '置信度',
      'evidence.model': '模型',
      'evidence.review': '复核状态',
      'evidence.action': '建议动作：{value}',

      'control.confirmEnable': '确认启用',
      'control.confirmDisable': '确认停用',
      'control.applyChange': '是否对 {title} 执行{action}？',

      'alert.acknowledge': '确认处理',
      'alert.justNow': '刚刚',
      'alert.minutesAgo': '{minutes} 分钟前',
      'alert.hoursAgo': '{hours} 小时前',
      'alert.dateShort': '{month}/{day}',

      'dynamic.alert.title.temperatureWarning': '温度预警',
      'dynamic.alert.title.aiImageWarning': 'AI 图像预警',
      'dynamic.alert.title.leakageCurrentCritical': '漏电流严重报警',
      'dynamic.alert.message.temperatureReached': '温度达到 {value} C。',
      'dynamic.alert.message.leakageReached': '漏电流达到 {value}mA。',
      'dynamic.alert.message.aiWindowNeedsConfirm': 'AI 复核检测到窗户开启，请人工确认。',
      'dynamic.risk.critical': '严重',
      'dynamic.risk.warning': '预警',
      'dynamic.risk.info': '提示',
      'dynamic.scene.environment': '环境',
      'dynamic.scene.power': '电源',
      'dynamic.scene.water': '水路',
      'dynamic.scene.security': '安防',
      'dynamic.scene.chemical': '危化品',
      'dynamic.scene.alert': '报警',
      'dynamic.scene.device': '设备',
      'dynamic.scene.general': '通用',
      'dynamic.deviceType.environmentSensor': '环境传感器',
      'dynamic.deviceType.mainPower': '总电源',
      'dynamic.deviceType.mainValve': '总阀门',
      'dynamic.deviceType.doorWindow': '门窗',
      'dynamic.deviceType.chemicalStorage': '危化品存储',
      'dynamic.deviceType.alertCenter': '报警中心',
      'dynamic.deviceType.powerMonitor': '电源监测器',
      'dynamic.deviceType.genericDevice': '通用设备',
      'dynamic.deviceType.unknown': '未知设备',
      'dynamic.reviewStatus.pendingReview': '待复核',
      'dynamic.reviewStatus.approved': '已通过',
      'dynamic.reviewStatus.rejected': '已驳回',
      'dynamic.recommendation.requestManualReview': '请求人工复核。',
      'dynamic.recommendation.verifySceneSafety': '请安排人员人工确认现场安全。',
      'dynamic.reason.waitingStructuredAnalysis': '等待后端结构化分析结果。',
      'dynamic.reason.waitingAiRetry': '图像已本地归档，等待后端 AI 服务重试。',

      'router.pageNotFound': '页面不存在',

      'role.admin': '管理员',
      'role.teacher': '教师',
      'role.graduate': '研究生',
      'role.undergraduate': '本科助理',

      'hazard.flammable': '易燃',
      'hazard.corrosive': '腐蚀性',
      'hazard.toxic': '有毒',
      'hazard.oxidizer': '氧化性',
      'hazard.compressedGas': '压缩气体',
      'hazard.irritant': '刺激性',
      'hazard.other': '其他',
    },
    'en': {
      'app.name': 'SmartLab',
      'app.selectLab': 'Select lab',
      'app.notLoggedIn': 'Not logged in',
      'app.openLabSelector': 'Open lab selector',
      'app.labsAndAccount': 'Labs and account',
      'app.language': 'Language',
      'app.languageChinese': 'Chinese',
      'app.languageEnglish': 'English',
      'app.smartLabSubtitle': 'Lab Safety Monitoring',

      'common.cancel': 'Cancel',
      'common.confirm': 'Confirm',
      'common.ok': 'OK',
      'common.login': 'Login',
      'common.logout': 'Logout',
      'common.submit': 'Submit',
      'common.search': 'Search',
      'common.on': 'On',
      'common.off': 'Off',
      'common.enable': 'Enable',
      'common.disable': 'Disable',

      'nav.home': 'Home',
      'nav.environment': 'Env',
      'nav.power': 'Power',
      'nav.security': 'Security',
      'nav.chemicals': 'Chem',

      'login.title': 'Login',
      'login.helper': 'Use student id, employee id, or admin account.',
      'login.username': 'Username',
      'login.usernameHint': 'student id / employee id / username',
      'login.enterUsername': 'Enter username',
      'login.password': 'Password',
      'login.passwordHint': 'Enter password',
      'login.enterPassword': 'Enter password',
      'login.remember': 'Remember',
      'login.forgotPassword': 'Forgot password',
      'login.registerRequest': 'Submit registration request',
      'login.passwordResetTitle': 'Password reset',
      'login.passwordResetDesc': 'Contact a lab administrator to reset this account.',
      'login.testAccounts': 'Test accounts\nadmin / admin123\nteacher / teacher123\ngraduate / graduate123\nstudent / student123',

      'register.title': 'Register',
      'register.desc': 'New accounts require admin review before login is allowed.',
      'register.name': 'Name',
      'register.studentOrEmployeeId': 'Student ID / Employee ID',
      'register.email': 'Email',
      'register.enterEmail': 'Enter email',
      'register.invalidEmail': 'Invalid email',
      'register.phone': 'Phone',
      'register.requestedRole': 'Requested role',
      'register.password': 'Password',
      'register.confirmPassword': 'Confirm password',
      'register.atLeast6Chars': 'At least 6 chars',
      'register.passwordMismatch': 'Passwords do not match',
      'register.required': 'Required',

      'labSelection.title': 'Select Lab',
      'labSelection.desc': 'This release is limited to the two labs defined in project docs.',
      'labSelection.noAccess': 'No lab access assigned',
      'labSelection.envCount': 'Env {count}',
      'labSelection.socketCount': 'Socket {count}',
      'labSelection.doorCount': 'Door {count}',
      'labSelection.windowCount': 'Window {count}',

      'dashboard.currentLab': 'Current lab',
      'dashboard.environment': 'Environment',
      'dashboard.power': 'Power',
      'dashboard.water': 'Water',
      'dashboard.doors': 'Doors',
      'dashboard.normal': 'Normal',
      'dashboard.review': 'Review',
      'dashboard.recentAlerts': 'Recent alerts',
      'dashboard.mqttOnline': 'MQTT online',
      'dashboard.mqttOffline': 'MQTT offline',
      'dashboard.noAlerts': 'No alerts',
      'dashboard.ack': 'Ack',
      'dashboard.safetyScore': 'Safety score: {score}',
      'dashboard.pendingAlerts': 'Pending alerts: {count}',

      'environment.title': 'Environment',
      'environment.evidenceTitle': 'AI evidence for environment',
      'environment.evidenceDesc': 'Use image review when hardware sensors are unavailable.',
      'environment.temp': 'Temp',
      'environment.humidity': 'Humidity',
      'environment.tempTrend': 'Temperature trend',
      'environment.voc': 'VOC {value} ppb',

      'power.title': 'Power',
      'power.evidenceTitle': 'AI evidence for power',
      'power.evidenceDesc': 'Review breakers, sockets and oven power safety from images.',
      'power.leakage': 'Leakage {value} mA',
      'power.noPermission': 'No device control permission',
      'power.confirmShutdownTitle': 'Confirm shutdown',
      'power.confirmShutdownDesc': 'Check lab safety before cutting main power.',
      'power.biometricReason': 'Confirm identity before shutdown',
      'power.powerValue': 'Power {value} W',
      'power.voltageValue': 'Voltage {value} V',
      'power.shutdown': 'Shutdown',
      'power.restore': 'Restore',

      'security.tabWater': 'Water',
      'security.tabDoors': 'Doors',
      'security.waterEvidenceTitle': 'AI evidence for water',
      'security.waterEvidenceDesc': 'Review valves, taps and leaks from photos.',
      'security.mainValve': 'Main valve',
      'security.open': 'Open',
      'security.closed': 'Closed',
      'security.doorsEvidenceTitle': 'AI evidence for doors and windows',
      'security.doorsEvidenceDesc': 'Review lock state and window opening angle from photos.',
      'security.locked': 'Locked',
      'security.unlocked': 'Unlocked',
      'security.windowAngle': 'Angle {angle}',

      'chem.searchHint': 'Search name, CAS, or cabinet',
      'chem.evidenceTitle': 'AI evidence for chemicals',
      'chem.evidenceDesc': 'Capture labels, cabinet status, and storage evidence.',
      'chem.noResults': 'No chemicals found for the current filter.',
      'chem.cas': 'CAS: {value}',
      'chem.cabinet': 'Cabinet: {cabinet} / {shelf}',
      'chem.stock': 'Stock: {quantity} {unit}',
      'chem.hazard': 'Hazard: {value}',
      'chem.checkIn': 'Check in',
      'chem.checkOut': 'Check out',
      'chem.checkInNote': 'Manual check-in from detail sheet',
      'chem.checkOutNote': 'Manual check-out from detail sheet',

      'alerts.title': 'Alerts',
      'alerts.evidenceTitle': 'AI evidence for alerts',
      'alerts.evidenceDesc': 'Attach images and AI review to pending alerts.',
      'alerts.ai': 'AI',
      'alerts.ack': 'Ack',
      'alerts.acked': 'Acked',

      'device.detailTitle': 'Device detail',
      'device.id': 'ID',
      'device.type': 'Type',
      'device.status': 'Status',
      'device.protocol': 'Protocol',
      'device.firmware': 'Firmware',
      'device.location': 'Location',
      'device.evidenceTitle': 'AI evidence for device',
      'device.evidenceDesc': 'Attach photos when device telemetry is unavailable.',
      'device.trend24h': '24h trend',
      'device.unknownDevice': 'Unknown device',
      'device.unknownLocation': 'Unknown',
      'device.currentLab': 'Current lab',
      'deviceStatus.online': 'Online',
      'deviceStatus.offline': 'Offline',
      'deviceStatus.warning': 'Warning',
      'deviceStatus.error': 'Error',

      'evidence.capture': 'Capture',
      'evidence.upload': 'Upload',
      'evidence.noResult': 'No AI result yet',
      'evidence.showLatest': 'Show latest AI result',
      'evidence.latestTitle': 'Latest AI inspection',
      'evidence.scene': 'Scene',
      'evidence.device': 'Device',
      'evidence.risk': 'Risk',
      'evidence.confidence': 'Confidence',
      'evidence.model': 'Model',
      'evidence.review': 'Review',
      'evidence.action': 'Action: {value}',

      'control.confirmEnable': 'Confirm enable',
      'control.confirmDisable': 'Confirm disable',
      'control.applyChange': 'Apply {action} to {title}?',

      'alert.acknowledge': 'Acknowledge',
      'alert.justNow': 'Just now',
      'alert.minutesAgo': '{minutes} min ago',
      'alert.hoursAgo': '{hours} h ago',
      'alert.dateShort': '{month}/{day}',

        'dynamic.alert.title.temperatureWarning': 'Temperature warning',
        'dynamic.alert.title.aiImageWarning': 'AI image warning',
        'dynamic.alert.title.leakageCurrentCritical': 'Leakage current critical',
        'dynamic.alert.message.temperatureReached': 'Temperature reached {value} C.',
        'dynamic.alert.message.leakageReached': 'Leakage current reached {value}mA.',
        'dynamic.alert.message.aiWindowNeedsConfirm':
          'AI review detected an open window that needs manual confirmation.',
        'dynamic.risk.critical': 'Critical',
        'dynamic.risk.warning': 'Warning',
        'dynamic.risk.info': 'Info',
        'dynamic.scene.environment': 'Environment',
        'dynamic.scene.power': 'Power',
        'dynamic.scene.water': 'Water',
        'dynamic.scene.security': 'Security',
        'dynamic.scene.chemical': 'Chemical',
        'dynamic.scene.alert': 'Alert',
        'dynamic.scene.device': 'Device',
        'dynamic.scene.general': 'General',
        'dynamic.deviceType.environmentSensor': 'Environment sensor',
        'dynamic.deviceType.mainPower': 'Main power',
        'dynamic.deviceType.mainValve': 'Main valve',
        'dynamic.deviceType.doorWindow': 'Doors and windows',
        'dynamic.deviceType.chemicalStorage': 'Chemical storage',
        'dynamic.deviceType.alertCenter': 'Alert center',
        'dynamic.deviceType.powerMonitor': 'Power monitor',
        'dynamic.deviceType.genericDevice': 'Generic device',
        'dynamic.deviceType.unknown': 'Unknown device',
        'dynamic.reviewStatus.pendingReview': 'Pending review',
        'dynamic.reviewStatus.approved': 'Approved',
        'dynamic.reviewStatus.rejected': 'Rejected',
        'dynamic.recommendation.requestManualReview': 'Request manual review.',
        'dynamic.recommendation.verifySceneSafety': 'Ask staff to verify scene safety manually.',
        'dynamic.reason.waitingStructuredAnalysis': 'Waiting for backend structured analysis.',
        'dynamic.reason.waitingAiRetry': 'Image archived locally. Waiting for backend AI service retry.',
        'dynamic.reason.doorNeedsReview': 'Door may be unlocked or not fully closed.',
        'dynamic.reason.windowNeedsReview': 'Window may be open and needs manual confirmation.',
        'dynamic.reason.waterNeedsReview': 'Water source may still be active or there are signs of leakage.',
        'dynamic.reason.powerNeedsReview': 'Power switch or socket state needs manual confirmation.',
        'dynamic.reason.ovenNeedsReview': 'Oven power state or surrounding area may be unsafe.',
        'dynamic.reason.chemicalNeedsReview': 'Chemical cabinet scene needs manual validation.',
        'dynamic.reason.alertNeedsReview': 'Alert evidence uploaded and queued for manual review.',

      'router.pageNotFound': 'Page not found',

      'role.admin': 'Admin',
      'role.teacher': 'Teacher',
      'role.graduate': 'Graduate',
      'role.undergraduate': 'Assistant',

      'hazard.flammable': 'Flammable',
      'hazard.corrosive': 'Corrosive',
      'hazard.toxic': 'Toxic',
      'hazard.oxidizer': 'Oxidizer',
      'hazard.compressedGas': 'Compressed gas',
      'hazard.irritant': 'Irritant',
      'hazard.other': 'Other',
    },
  };
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => locale.languageCode == 'zh' || locale.languageCode == 'en';

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
